;;;; src/infos-table.lisp — GENERATED FILE, DO NOT EDIT.
;;;;
;;;; Produced by generator/generate-tables.lisp from the libcurl 8.21.0
;;;; headers in /opt/homebrew/opt/curl/include/curl/
;;;;
;;;; Regenerate with `make tables'.  78 info values.
;;;; The committed output is what the library loads, so a build never
;;;; needs curl headers -- and the test suite checks this table against
;;;; whatever libcurl is actually loaded, which is what catches drift.

(in-package #:libcurl)

(register-infos
  '(
   (:effective-url #x100001 :string "CURLINFO_EFFECTIVE_URL" NIL)
   (:response-code #x200002 :long "CURLINFO_RESPONSE_CODE" NIL)
   (:total-time #x300003 :double "CURLINFO_TOTAL_TIME" NIL)
   (:namelookup-time #x300004 :double "CURLINFO_NAMELOOKUP_TIME" NIL)
   (:connect-time #x300005 :double "CURLINFO_CONNECT_TIME" NIL)
   (:pretransfer-time #x300006 :double "CURLINFO_PRETRANSFER_TIME" NIL)
   (:size-upload #x300007 :double "CURLINFO_SIZE_UPLOAD" "7.55.0")
   (:size-upload-t #x600007 :off-t "CURLINFO_SIZE_UPLOAD_T" NIL)
   (:size-download #x300008 :double "CURLINFO_SIZE_DOWNLOAD" "7.55.0")
   (:size-download-t #x600008 :off-t "CURLINFO_SIZE_DOWNLOAD_T" NIL)
   (:speed-download #x300009 :double "CURLINFO_SPEED_DOWNLOAD" "7.55.0")
   (:speed-download-t #x600009 :off-t "CURLINFO_SPEED_DOWNLOAD_T" NIL)
   (:speed-upload #x30000A :double "CURLINFO_SPEED_UPLOAD" "7.55.0")
   (:speed-upload-t #x60000A :off-t "CURLINFO_SPEED_UPLOAD_T" NIL)
   (:header-size #x20000B :long "CURLINFO_HEADER_SIZE" NIL)
   (:request-size #x20000C :long "CURLINFO_REQUEST_SIZE" NIL)
   (:ssl-verifyresult #x20000D :long "CURLINFO_SSL_VERIFYRESULT" NIL)
   (:filetime #x20000E :long "CURLINFO_FILETIME" NIL)
   (:filetime-t #x60000E :off-t "CURLINFO_FILETIME_T" NIL)
   (:content-length-download #x30000F :double "CURLINFO_CONTENT_LENGTH_DOWNLOAD" "7.55.0")
   (:content-length-download-t #x60000F :off-t "CURLINFO_CONTENT_LENGTH_DOWNLOAD_T" NIL)
   (:content-length-upload #x300010 :double "CURLINFO_CONTENT_LENGTH_UPLOAD" "7.55.0")
   (:content-length-upload-t #x600010 :off-t "CURLINFO_CONTENT_LENGTH_UPLOAD_T" NIL)
   (:starttransfer-time #x300011 :double "CURLINFO_STARTTRANSFER_TIME" NIL)
   (:content-type #x100012 :string "CURLINFO_CONTENT_TYPE" NIL)
   (:redirect-time #x300013 :double "CURLINFO_REDIRECT_TIME" NIL)
   (:redirect-count #x200014 :long "CURLINFO_REDIRECT_COUNT" NIL)
   (:private #x100015 :pointer "CURLINFO_PRIVATE" NIL)
   (:http-connectcode #x200016 :long "CURLINFO_HTTP_CONNECTCODE" NIL)
   (:httpauth-avail #x200017 :long "CURLINFO_HTTPAUTH_AVAIL" NIL)
   (:proxyauth-avail #x200018 :long "CURLINFO_PROXYAUTH_AVAIL" NIL)
   (:os-errno #x200019 :long "CURLINFO_OS_ERRNO" NIL)
   (:num-connects #x20001A :long "CURLINFO_NUM_CONNECTS" NIL)
   (:ssl-engines #x40001B :slist "CURLINFO_SSL_ENGINES" NIL)
   (:cookielist #x40001C :slist "CURLINFO_COOKIELIST" NIL)
   (:lastsocket #x20001D :long "CURLINFO_LASTSOCKET" "7.45.0")
   (:ftp-entry-path #x10001E :string "CURLINFO_FTP_ENTRY_PATH" NIL)
   (:redirect-url #x10001F :string "CURLINFO_REDIRECT_URL" NIL)
   (:primary-ip #x100020 :string "CURLINFO_PRIMARY_IP" NIL)
   (:appconnect-time #x300021 :double "CURLINFO_APPCONNECT_TIME" NIL)
   (:certinfo #x400022 :pointer "CURLINFO_CERTINFO" NIL)
   (:condition-unmet #x200023 :long "CURLINFO_CONDITION_UNMET" NIL)
   (:rtsp-session-id #x100024 :string "CURLINFO_RTSP_SESSION_ID" NIL)
   (:rtsp-client-cseq #x200025 :long "CURLINFO_RTSP_CLIENT_CSEQ" NIL)
   (:rtsp-server-cseq #x200026 :long "CURLINFO_RTSP_SERVER_CSEQ" NIL)
   (:rtsp-cseq-recv #x200027 :long "CURLINFO_RTSP_CSEQ_RECV" NIL)
   (:primary-port #x200028 :long "CURLINFO_PRIMARY_PORT" NIL)
   (:local-ip #x100029 :string "CURLINFO_LOCAL_IP" NIL)
   (:local-port #x20002A :long "CURLINFO_LOCAL_PORT" NIL)
   (:tls-session #x40002B :pointer "CURLINFO_TLS_SESSION" "7.48.0")
   (:activesocket #x50002C :socket "CURLINFO_ACTIVESOCKET" NIL)
   (:tls-ssl-ptr #x40002D :pointer "CURLINFO_TLS_SSL_PTR" NIL)
   (:http-version #x20002E :long "CURLINFO_HTTP_VERSION" NIL)
   (:proxy-ssl-verifyresult #x20002F :long "CURLINFO_PROXY_SSL_VERIFYRESULT" NIL)
   (:protocol #x200030 :long "CURLINFO_PROTOCOL" "7.85.0")
   (:scheme #x100031 :string "CURLINFO_SCHEME" NIL)
   (:total-time-t #x600032 :off-t "CURLINFO_TOTAL_TIME_T" NIL)
   (:namelookup-time-t #x600033 :off-t "CURLINFO_NAMELOOKUP_TIME_T" NIL)
   (:connect-time-t #x600034 :off-t "CURLINFO_CONNECT_TIME_T" NIL)
   (:pretransfer-time-t #x600035 :off-t "CURLINFO_PRETRANSFER_TIME_T" NIL)
   (:starttransfer-time-t #x600036 :off-t "CURLINFO_STARTTRANSFER_TIME_T" NIL)
   (:redirect-time-t #x600037 :off-t "CURLINFO_REDIRECT_TIME_T" NIL)
   (:appconnect-time-t #x600038 :off-t "CURLINFO_APPCONNECT_TIME_T" NIL)
   (:retry-after #x600039 :off-t "CURLINFO_RETRY_AFTER" NIL)
   (:effective-method #x10003A :string "CURLINFO_EFFECTIVE_METHOD" NIL)
   (:proxy-error #x20003B :long "CURLINFO_PROXY_ERROR" NIL)
   (:referer #x10003C :string "CURLINFO_REFERER" NIL)
   (:cainfo #x10003D :string "CURLINFO_CAINFO" NIL)
   (:capath #x10003E :string "CURLINFO_CAPATH" NIL)
   (:xfer-id #x60003F :off-t "CURLINFO_XFER_ID" NIL)
   (:conn-id #x600040 :off-t "CURLINFO_CONN_ID" NIL)
   (:queue-time-t #x600041 :off-t "CURLINFO_QUEUE_TIME_T" NIL)
   (:used-proxy #x200042 :long "CURLINFO_USED_PROXY" NIL)
   (:posttransfer-time-t #x600043 :off-t "CURLINFO_POSTTRANSFER_TIME_T" NIL)
   (:earlydata-sent-t #x600044 :off-t "CURLINFO_EARLYDATA_SENT_T" NIL)
   (:httpauth-used #x200045 :long "CURLINFO_HTTPAUTH_USED" NIL)
   (:proxyauth-used #x200046 :long "CURLINFO_PROXYAUTH_USED" NIL)
   (:size-delivered #x600047 :off-t "CURLINFO_SIZE_DELIVERED" NIL)
   ))
