;;;; src/options-table.lisp — GENERATED FILE, DO NOT EDIT.
;;;;
;;;; Produced by generator/generate-tables.lisp from the libcurl 8.21.0
;;;; headers in /opt/homebrew/opt/curl/include/curl/
;;;;
;;;; Regenerate with `make tables'.  327 options (308 declared, 19 aliases) and 21 multi options.
;;;; The committed output is what the library loads, so a build never
;;;; needs curl headers -- and the test suite checks this table against
;;;; whatever libcurl is actually loaded, which is what catches drift.

(in-package #:curlcl)

(register-options
  '(
   (:writedata 10001 :cbpoint "CURLOPT_WRITEDATA" NIL NIL NIL)
   (:url 10002 :stringpoint "CURLOPT_URL" NIL NIL NIL)
   (:port 3 :long "CURLOPT_PORT" NIL NIL NIL)
   (:proxy 10004 :stringpoint "CURLOPT_PROXY" NIL NIL NIL)
   (:userpwd 10005 :stringpoint "CURLOPT_USERPWD" NIL NIL NIL)
   (:proxyuserpwd 10006 :stringpoint "CURLOPT_PROXYUSERPWD" NIL NIL NIL)
   (:range 10007 :stringpoint "CURLOPT_RANGE" NIL NIL NIL)
   (:readdata 10009 :cbpoint "CURLOPT_READDATA" NIL NIL NIL)
   (:errorbuffer 10010 :objectpoint "CURLOPT_ERRORBUFFER" NIL NIL NIL)
   (:writefunction 20011 :functionpoint "CURLOPT_WRITEFUNCTION" NIL NIL NIL)
   (:readfunction 20012 :functionpoint "CURLOPT_READFUNCTION" NIL NIL NIL)
   (:timeout 13 :long "CURLOPT_TIMEOUT" NIL NIL NIL)
   (:infilesize 14 :long "CURLOPT_INFILESIZE" NIL NIL NIL)
   (:postfields 10015 :objectpoint "CURLOPT_POSTFIELDS" NIL NIL NIL)
   (:referer 10016 :stringpoint "CURLOPT_REFERER" NIL NIL NIL)
   (:ftpport 10017 :stringpoint "CURLOPT_FTPPORT" NIL NIL NIL)
   (:useragent 10018 :stringpoint "CURLOPT_USERAGENT" NIL NIL NIL)
   (:low-speed-limit 19 :long "CURLOPT_LOW_SPEED_LIMIT" NIL NIL NIL)
   (:low-speed-time 20 :long "CURLOPT_LOW_SPEED_TIME" NIL NIL NIL)
   (:resume-from 21 :long "CURLOPT_RESUME_FROM" NIL NIL NIL)
   (:cookie 10022 :stringpoint "CURLOPT_COOKIE" NIL NIL NIL)
   (:httpheader 10023 :slistpoint "CURLOPT_HTTPHEADER" NIL NIL NIL)
   (:sslcert 10025 :stringpoint "CURLOPT_SSLCERT" NIL NIL NIL)
   (:keypasswd 10026 :stringpoint "CURLOPT_KEYPASSWD" NIL NIL NIL)
   (:crlf 27 :long "CURLOPT_CRLF" NIL NIL NIL)
   (:quote 10028 :slistpoint "CURLOPT_QUOTE" NIL NIL NIL)
   (:headerdata 10029 :cbpoint "CURLOPT_HEADERDATA" NIL NIL NIL)
   (:cookiefile 10031 :stringpoint "CURLOPT_COOKIEFILE" NIL NIL NIL)
   (:sslversion 32 :values "CURLOPT_SSLVERSION" NIL NIL NIL)
   (:timecondition 33 :values "CURLOPT_TIMECONDITION" NIL NIL NIL)
   (:timevalue 34 :long "CURLOPT_TIMEVALUE" NIL NIL NIL)
   (:customrequest 10036 :stringpoint "CURLOPT_CUSTOMREQUEST" NIL NIL NIL)
   (:stderr 10037 :objectpoint "CURLOPT_STDERR" NIL NIL NIL)
   (:postquote 10039 :slistpoint "CURLOPT_POSTQUOTE" NIL NIL NIL)
   (:verbose 41 :long "CURLOPT_VERBOSE" NIL NIL NIL)
   (:header 42 :long "CURLOPT_HEADER" NIL NIL NIL)
   (:noprogress 43 :long "CURLOPT_NOPROGRESS" NIL NIL NIL)
   (:nobody 44 :long "CURLOPT_NOBODY" NIL NIL NIL)
   (:failonerror 45 :long "CURLOPT_FAILONERROR" NIL NIL NIL)
   (:upload 46 :long "CURLOPT_UPLOAD" NIL NIL NIL)
   (:post 47 :long "CURLOPT_POST" NIL NIL NIL)
   (:dirlistonly 48 :long "CURLOPT_DIRLISTONLY" NIL NIL NIL)
   (:append 50 :long "CURLOPT_APPEND" NIL NIL NIL)
   (:netrc 51 :values "CURLOPT_NETRC" NIL NIL NIL)
   (:followlocation 52 :long "CURLOPT_FOLLOWLOCATION" NIL NIL NIL)
   (:transfertext 53 :long "CURLOPT_TRANSFERTEXT" NIL NIL NIL)
   (:xferinfodata 10057 :cbpoint "CURLOPT_XFERINFODATA" NIL NIL NIL)
   (:autoreferer 58 :long "CURLOPT_AUTOREFERER" NIL NIL NIL)
   (:proxyport 59 :long "CURLOPT_PROXYPORT" NIL NIL NIL)
   (:postfieldsize 60 :long "CURLOPT_POSTFIELDSIZE" NIL NIL NIL)
   (:httpproxytunnel 61 :long "CURLOPT_HTTPPROXYTUNNEL" NIL NIL NIL)
   (:interface 10062 :stringpoint "CURLOPT_INTERFACE" NIL NIL NIL)
   (:ssl-verifypeer 64 :long "CURLOPT_SSL_VERIFYPEER" NIL NIL NIL)
   (:cainfo 10065 :stringpoint "CURLOPT_CAINFO" NIL NIL NIL)
   (:maxredirs 68 :long "CURLOPT_MAXREDIRS" NIL NIL NIL)
   (:filetime 69 :long "CURLOPT_FILETIME" NIL NIL NIL)
   (:telnetoptions 10070 :slistpoint "CURLOPT_TELNETOPTIONS" NIL NIL NIL)
   (:maxconnects 71 :long "CURLOPT_MAXCONNECTS" NIL NIL NIL)
   (:fresh-connect 74 :long "CURLOPT_FRESH_CONNECT" NIL NIL NIL)
   (:forbid-reuse 75 :long "CURLOPT_FORBID_REUSE" NIL NIL NIL)
   (:connecttimeout 78 :long "CURLOPT_CONNECTTIMEOUT" NIL NIL NIL)
   (:headerfunction 20079 :functionpoint "CURLOPT_HEADERFUNCTION" NIL NIL NIL)
   (:httpget 80 :long "CURLOPT_HTTPGET" NIL NIL NIL)
   (:ssl-verifyhost 81 :long "CURLOPT_SSL_VERIFYHOST" NIL NIL NIL)
   (:cookiejar 10082 :stringpoint "CURLOPT_COOKIEJAR" NIL NIL NIL)
   (:ssl-cipher-list 10083 :stringpoint "CURLOPT_SSL_CIPHER_LIST" NIL NIL NIL)
   (:http-version 84 :values "CURLOPT_HTTP_VERSION" NIL NIL NIL)
   (:ftp-use-epsv 85 :long "CURLOPT_FTP_USE_EPSV" NIL NIL NIL)
   (:sslcerttype 10086 :stringpoint "CURLOPT_SSLCERTTYPE" NIL NIL NIL)
   (:sslkey 10087 :stringpoint "CURLOPT_SSLKEY" NIL NIL NIL)
   (:sslkeytype 10088 :stringpoint "CURLOPT_SSLKEYTYPE" NIL NIL NIL)
   (:sslengine 10089 :stringpoint "CURLOPT_SSLENGINE" NIL NIL NIL)
   (:sslengine-default 90 :long "CURLOPT_SSLENGINE_DEFAULT" NIL NIL NIL)
   (:dns-cache-timeout 92 :long "CURLOPT_DNS_CACHE_TIMEOUT" NIL NIL NIL)
   (:prequote 10093 :slistpoint "CURLOPT_PREQUOTE" NIL NIL NIL)
   (:debugfunction 20094 :functionpoint "CURLOPT_DEBUGFUNCTION" NIL NIL NIL)
   (:debugdata 10095 :cbpoint "CURLOPT_DEBUGDATA" NIL NIL NIL)
   (:cookiesession 96 :long "CURLOPT_COOKIESESSION" NIL NIL NIL)
   (:capath 10097 :stringpoint "CURLOPT_CAPATH" NIL NIL NIL)
   (:buffersize 98 :long "CURLOPT_BUFFERSIZE" NIL NIL NIL)
   (:nosignal 99 :long "CURLOPT_NOSIGNAL" NIL NIL NIL)
   (:share 10100 :objectpoint "CURLOPT_SHARE" NIL NIL NIL)
   (:proxytype 101 :values "CURLOPT_PROXYTYPE" NIL NIL NIL)
   (:accept-encoding 10102 :stringpoint "CURLOPT_ACCEPT_ENCODING" NIL NIL NIL)
   (:private 10103 :objectpoint "CURLOPT_PRIVATE" NIL NIL NIL)
   (:http200aliases 10104 :slistpoint "CURLOPT_HTTP200ALIASES" NIL NIL NIL)
   (:unrestricted-auth 105 :long "CURLOPT_UNRESTRICTED_AUTH" NIL NIL NIL)
   (:ftp-use-eprt 106 :long "CURLOPT_FTP_USE_EPRT" NIL NIL NIL)
   (:httpauth 107 :values "CURLOPT_HTTPAUTH" NIL NIL NIL)
   (:ssl-ctx-function 20108 :functionpoint "CURLOPT_SSL_CTX_FUNCTION" NIL NIL NIL)
   (:ssl-ctx-data 10109 :cbpoint "CURLOPT_SSL_CTX_DATA" NIL NIL NIL)
   (:ftp-create-missing-dirs 110 :long "CURLOPT_FTP_CREATE_MISSING_DIRS" NIL NIL NIL)
   (:proxyauth 111 :values "CURLOPT_PROXYAUTH" NIL NIL NIL)
   (:server-response-timeout 112 :long "CURLOPT_SERVER_RESPONSE_TIMEOUT" NIL NIL NIL)
   (:ipresolve 113 :values "CURLOPT_IPRESOLVE" NIL NIL NIL)
   (:maxfilesize 114 :long "CURLOPT_MAXFILESIZE" NIL NIL NIL)
   (:infilesize-large 30115 :off-t "CURLOPT_INFILESIZE_LARGE" NIL NIL NIL)
   (:resume-from-large 30116 :off-t "CURLOPT_RESUME_FROM_LARGE" NIL NIL NIL)
   (:maxfilesize-large 30117 :off-t "CURLOPT_MAXFILESIZE_LARGE" NIL NIL NIL)
   (:netrc-file 10118 :stringpoint "CURLOPT_NETRC_FILE" NIL NIL NIL)
   (:use-ssl 119 :values "CURLOPT_USE_SSL" NIL NIL NIL)
   (:postfieldsize-large 30120 :off-t "CURLOPT_POSTFIELDSIZE_LARGE" NIL NIL NIL)
   (:tcp-nodelay 121 :long "CURLOPT_TCP_NODELAY" NIL NIL NIL)
   (:ftpsslauth 129 :values "CURLOPT_FTPSSLAUTH" NIL NIL NIL)
   (:ftp-account 10134 :stringpoint "CURLOPT_FTP_ACCOUNT" NIL NIL NIL)
   (:cookielist 10135 :stringpoint "CURLOPT_COOKIELIST" NIL NIL NIL)
   (:ignore-content-length 136 :long "CURLOPT_IGNORE_CONTENT_LENGTH" NIL NIL NIL)
   (:ftp-skip-pasv-ip 137 :long "CURLOPT_FTP_SKIP_PASV_IP" NIL NIL NIL)
   (:ftp-filemethod 138 :values "CURLOPT_FTP_FILEMETHOD" NIL NIL NIL)
   (:localport 139 :long "CURLOPT_LOCALPORT" NIL NIL NIL)
   (:localportrange 140 :long "CURLOPT_LOCALPORTRANGE" NIL NIL NIL)
   (:connect-only 141 :long "CURLOPT_CONNECT_ONLY" NIL NIL NIL)
   (:max-send-speed-large 30145 :off-t "CURLOPT_MAX_SEND_SPEED_LARGE" NIL NIL NIL)
   (:max-recv-speed-large 30146 :off-t "CURLOPT_MAX_RECV_SPEED_LARGE" NIL NIL NIL)
   (:ftp-alternative-to-user 10147 :stringpoint "CURLOPT_FTP_ALTERNATIVE_TO_USER" NIL NIL NIL)
   (:sockoptfunction 20148 :functionpoint "CURLOPT_SOCKOPTFUNCTION" NIL NIL NIL)
   (:sockoptdata 10149 :cbpoint "CURLOPT_SOCKOPTDATA" NIL NIL NIL)
   (:ssl-sessionid-cache 150 :long "CURLOPT_SSL_SESSIONID_CACHE" NIL NIL NIL)
   (:ssh-auth-types 151 :values "CURLOPT_SSH_AUTH_TYPES" NIL NIL NIL)
   (:ssh-public-keyfile 10152 :stringpoint "CURLOPT_SSH_PUBLIC_KEYFILE" NIL NIL NIL)
   (:ssh-private-keyfile 10153 :stringpoint "CURLOPT_SSH_PRIVATE_KEYFILE" NIL NIL NIL)
   (:ftp-ssl-ccc 154 :long "CURLOPT_FTP_SSL_CCC" NIL NIL NIL)
   (:timeout-ms 155 :long "CURLOPT_TIMEOUT_MS" NIL NIL NIL)
   (:connecttimeout-ms 156 :long "CURLOPT_CONNECTTIMEOUT_MS" NIL NIL NIL)
   (:http-transfer-decoding 157 :long "CURLOPT_HTTP_TRANSFER_DECODING" NIL NIL NIL)
   (:http-content-decoding 158 :long "CURLOPT_HTTP_CONTENT_DECODING" NIL NIL NIL)
   (:new-file-perms 159 :long "CURLOPT_NEW_FILE_PERMS" NIL NIL NIL)
   (:new-directory-perms 160 :long "CURLOPT_NEW_DIRECTORY_PERMS" NIL NIL NIL)
   (:postredir 161 :values "CURLOPT_POSTREDIR" NIL NIL NIL)
   (:ssh-host-public-key-md5 10162 :stringpoint "CURLOPT_SSH_HOST_PUBLIC_KEY_MD5" NIL NIL NIL)
   (:opensocketfunction 20163 :functionpoint "CURLOPT_OPENSOCKETFUNCTION" NIL NIL NIL)
   (:opensocketdata 10164 :cbpoint "CURLOPT_OPENSOCKETDATA" NIL NIL NIL)
   (:copypostfields 10165 :objectpoint "CURLOPT_COPYPOSTFIELDS" NIL NIL NIL)
   (:proxy-transfer-mode 166 :long "CURLOPT_PROXY_TRANSFER_MODE" NIL NIL NIL)
   (:seekfunction 20167 :functionpoint "CURLOPT_SEEKFUNCTION" NIL NIL NIL)
   (:seekdata 10168 :cbpoint "CURLOPT_SEEKDATA" NIL NIL NIL)
   (:crlfile 10169 :stringpoint "CURLOPT_CRLFILE" NIL NIL NIL)
   (:issuercert 10170 :stringpoint "CURLOPT_ISSUERCERT" NIL NIL NIL)
   (:address-scope 171 :long "CURLOPT_ADDRESS_SCOPE" NIL NIL NIL)
   (:certinfo 172 :long "CURLOPT_CERTINFO" NIL NIL NIL)
   (:username 10173 :stringpoint "CURLOPT_USERNAME" NIL NIL NIL)
   (:password 10174 :stringpoint "CURLOPT_PASSWORD" NIL NIL NIL)
   (:proxyusername 10175 :stringpoint "CURLOPT_PROXYUSERNAME" NIL NIL NIL)
   (:proxypassword 10176 :stringpoint "CURLOPT_PROXYPASSWORD" NIL NIL NIL)
   (:noproxy 10177 :stringpoint "CURLOPT_NOPROXY" NIL NIL NIL)
   (:tftp-blksize 178 :long "CURLOPT_TFTP_BLKSIZE" NIL NIL NIL)
   (:socks5-gssapi-nec 180 :long "CURLOPT_SOCKS5_GSSAPI_NEC" NIL NIL NIL)
   (:ssh-knownhosts 10183 :stringpoint "CURLOPT_SSH_KNOWNHOSTS" NIL NIL NIL)
   (:ssh-keyfunction 20184 :functionpoint "CURLOPT_SSH_KEYFUNCTION" NIL NIL NIL)
   (:ssh-keydata 10185 :cbpoint "CURLOPT_SSH_KEYDATA" NIL NIL NIL)
   (:mail-from 10186 :stringpoint "CURLOPT_MAIL_FROM" NIL NIL NIL)
   (:mail-rcpt 10187 :slistpoint "CURLOPT_MAIL_RCPT" NIL NIL NIL)
   (:ftp-use-pret 188 :long "CURLOPT_FTP_USE_PRET" NIL NIL NIL)
   (:rtsp-request 189 :values "CURLOPT_RTSP_REQUEST" NIL NIL NIL)
   (:rtsp-session-id 10190 :stringpoint "CURLOPT_RTSP_SESSION_ID" NIL NIL NIL)
   (:rtsp-stream-uri 10191 :stringpoint "CURLOPT_RTSP_STREAM_URI" NIL NIL NIL)
   (:rtsp-transport 10192 :stringpoint "CURLOPT_RTSP_TRANSPORT" NIL NIL NIL)
   (:rtsp-client-cseq 193 :long "CURLOPT_RTSP_CLIENT_CSEQ" NIL NIL NIL)
   (:rtsp-server-cseq 194 :long "CURLOPT_RTSP_SERVER_CSEQ" NIL NIL NIL)
   (:interleavedata 10195 :cbpoint "CURLOPT_INTERLEAVEDATA" NIL NIL NIL)
   (:interleavefunction 20196 :functionpoint "CURLOPT_INTERLEAVEFUNCTION" NIL NIL NIL)
   (:wildcardmatch 197 :long "CURLOPT_WILDCARDMATCH" NIL NIL NIL)
   (:chunk-bgn-function 20198 :functionpoint "CURLOPT_CHUNK_BGN_FUNCTION" NIL NIL NIL)
   (:chunk-end-function 20199 :functionpoint "CURLOPT_CHUNK_END_FUNCTION" NIL NIL NIL)
   (:fnmatch-function 20200 :functionpoint "CURLOPT_FNMATCH_FUNCTION" NIL NIL NIL)
   (:chunk-data 10201 :cbpoint "CURLOPT_CHUNK_DATA" NIL NIL NIL)
   (:fnmatch-data 10202 :cbpoint "CURLOPT_FNMATCH_DATA" NIL NIL NIL)
   (:resolve 10203 :slistpoint "CURLOPT_RESOLVE" NIL NIL NIL)
   (:tlsauth-username 10204 :stringpoint "CURLOPT_TLSAUTH_USERNAME" NIL NIL NIL)
   (:tlsauth-password 10205 :stringpoint "CURLOPT_TLSAUTH_PASSWORD" NIL NIL NIL)
   (:tlsauth-type 10206 :stringpoint "CURLOPT_TLSAUTH_TYPE" NIL NIL NIL)
   (:transfer-encoding 207 :long "CURLOPT_TRANSFER_ENCODING" NIL NIL NIL)
   (:closesocketfunction 20208 :functionpoint "CURLOPT_CLOSESOCKETFUNCTION" NIL NIL NIL)
   (:closesocketdata 10209 :cbpoint "CURLOPT_CLOSESOCKETDATA" NIL NIL NIL)
   (:gssapi-delegation 210 :values "CURLOPT_GSSAPI_DELEGATION" NIL NIL NIL)
   (:dns-servers 10211 :stringpoint "CURLOPT_DNS_SERVERS" NIL NIL NIL)
   (:accepttimeout-ms 212 :long "CURLOPT_ACCEPTTIMEOUT_MS" NIL NIL NIL)
   (:tcp-keepalive 213 :long "CURLOPT_TCP_KEEPALIVE" NIL NIL NIL)
   (:tcp-keepidle 214 :long "CURLOPT_TCP_KEEPIDLE" NIL NIL NIL)
   (:tcp-keepintvl 215 :long "CURLOPT_TCP_KEEPINTVL" NIL NIL NIL)
   (:ssl-options 216 :values "CURLOPT_SSL_OPTIONS" NIL NIL NIL)
   (:mail-auth 10217 :stringpoint "CURLOPT_MAIL_AUTH" NIL NIL NIL)
   (:sasl-ir 218 :long "CURLOPT_SASL_IR" NIL NIL NIL)
   (:xferinfofunction 20219 :functionpoint "CURLOPT_XFERINFOFUNCTION" NIL NIL NIL)
   (:xoauth2-bearer 10220 :stringpoint "CURLOPT_XOAUTH2_BEARER" NIL NIL NIL)
   (:dns-interface 10221 :stringpoint "CURLOPT_DNS_INTERFACE" NIL NIL NIL)
   (:dns-local-ip4 10222 :stringpoint "CURLOPT_DNS_LOCAL_IP4" NIL NIL NIL)
   (:dns-local-ip6 10223 :stringpoint "CURLOPT_DNS_LOCAL_IP6" NIL NIL NIL)
   (:login-options 10224 :stringpoint "CURLOPT_LOGIN_OPTIONS" NIL NIL NIL)
   (:ssl-enable-alpn 226 :long "CURLOPT_SSL_ENABLE_ALPN" NIL NIL NIL)
   (:expect-100-timeout-ms 227 :long "CURLOPT_EXPECT_100_TIMEOUT_MS" NIL NIL NIL)
   (:proxyheader 10228 :slistpoint "CURLOPT_PROXYHEADER" NIL NIL NIL)
   (:headeropt 229 :values "CURLOPT_HEADEROPT" NIL NIL NIL)
   (:pinnedpublickey 10230 :stringpoint "CURLOPT_PINNEDPUBLICKEY" NIL NIL NIL)
   (:unix-socket-path 10231 :stringpoint "CURLOPT_UNIX_SOCKET_PATH" NIL NIL NIL)
   (:ssl-verifystatus 232 :long "CURLOPT_SSL_VERIFYSTATUS" NIL NIL NIL)
   (:path-as-is 234 :long "CURLOPT_PATH_AS_IS" NIL NIL NIL)
   (:proxy-service-name 10235 :stringpoint "CURLOPT_PROXY_SERVICE_NAME" NIL NIL NIL)
   (:service-name 10236 :stringpoint "CURLOPT_SERVICE_NAME" NIL NIL NIL)
   (:pipewait 237 :long "CURLOPT_PIPEWAIT" NIL NIL NIL)
   (:default-protocol 10238 :stringpoint "CURLOPT_DEFAULT_PROTOCOL" NIL NIL NIL)
   (:stream-weight 239 :long "CURLOPT_STREAM_WEIGHT" NIL NIL NIL)
   (:tftp-no-options 242 :long "CURLOPT_TFTP_NO_OPTIONS" NIL NIL NIL)
   (:connect-to 10243 :slistpoint "CURLOPT_CONNECT_TO" NIL NIL NIL)
   (:tcp-fastopen 244 :long "CURLOPT_TCP_FASTOPEN" NIL NIL NIL)
   (:keep-sending-on-error 245 :long "CURLOPT_KEEP_SENDING_ON_ERROR" NIL NIL NIL)
   (:proxy-cainfo 10246 :stringpoint "CURLOPT_PROXY_CAINFO" NIL NIL NIL)
   (:proxy-capath 10247 :stringpoint "CURLOPT_PROXY_CAPATH" NIL NIL NIL)
   (:proxy-ssl-verifypeer 248 :long "CURLOPT_PROXY_SSL_VERIFYPEER" NIL NIL NIL)
   (:proxy-ssl-verifyhost 249 :long "CURLOPT_PROXY_SSL_VERIFYHOST" NIL NIL NIL)
   (:proxy-sslversion 250 :values "CURLOPT_PROXY_SSLVERSION" NIL NIL NIL)
   (:proxy-tlsauth-username 10251 :stringpoint "CURLOPT_PROXY_TLSAUTH_USERNAME" NIL NIL NIL)
   (:proxy-tlsauth-password 10252 :stringpoint "CURLOPT_PROXY_TLSAUTH_PASSWORD" NIL NIL NIL)
   (:proxy-tlsauth-type 10253 :stringpoint "CURLOPT_PROXY_TLSAUTH_TYPE" NIL NIL NIL)
   (:proxy-sslcert 10254 :stringpoint "CURLOPT_PROXY_SSLCERT" NIL NIL NIL)
   (:proxy-sslcerttype 10255 :stringpoint "CURLOPT_PROXY_SSLCERTTYPE" NIL NIL NIL)
   (:proxy-sslkey 10256 :stringpoint "CURLOPT_PROXY_SSLKEY" NIL NIL NIL)
   (:proxy-sslkeytype 10257 :stringpoint "CURLOPT_PROXY_SSLKEYTYPE" NIL NIL NIL)
   (:proxy-keypasswd 10258 :stringpoint "CURLOPT_PROXY_KEYPASSWD" NIL NIL NIL)
   (:proxy-ssl-cipher-list 10259 :stringpoint "CURLOPT_PROXY_SSL_CIPHER_LIST" NIL NIL NIL)
   (:proxy-crlfile 10260 :stringpoint "CURLOPT_PROXY_CRLFILE" NIL NIL NIL)
   (:proxy-ssl-options 261 :long "CURLOPT_PROXY_SSL_OPTIONS" NIL NIL NIL)
   (:pre-proxy 10262 :stringpoint "CURLOPT_PRE_PROXY" NIL NIL NIL)
   (:proxy-pinnedpublickey 10263 :stringpoint "CURLOPT_PROXY_PINNEDPUBLICKEY" NIL NIL NIL)
   (:abstract-unix-socket 10264 :stringpoint "CURLOPT_ABSTRACT_UNIX_SOCKET" NIL NIL NIL)
   (:suppress-connect-headers 265 :long "CURLOPT_SUPPRESS_CONNECT_HEADERS" NIL NIL NIL)
   (:request-target 10266 :stringpoint "CURLOPT_REQUEST_TARGET" NIL NIL NIL)
   (:socks5-auth 267 :long "CURLOPT_SOCKS5_AUTH" NIL NIL NIL)
   (:ssh-compression 268 :long "CURLOPT_SSH_COMPRESSION" NIL NIL NIL)
   (:mimepost 10269 :objectpoint "CURLOPT_MIMEPOST" NIL NIL NIL)
   (:timevalue-large 30270 :off-t "CURLOPT_TIMEVALUE_LARGE" NIL NIL NIL)
   (:happy-eyeballs-timeout-ms 271 :long "CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS" NIL NIL NIL)
   (:resolver-start-function 20272 :functionpoint "CURLOPT_RESOLVER_START_FUNCTION" NIL NIL NIL)
   (:resolver-start-data 10273 :cbpoint "CURLOPT_RESOLVER_START_DATA" NIL NIL NIL)
   (:haproxyprotocol 274 :long "CURLOPT_HAPROXYPROTOCOL" NIL NIL NIL)
   (:dns-shuffle-addresses 275 :long "CURLOPT_DNS_SHUFFLE_ADDRESSES" NIL NIL NIL)
   (:tls13-ciphers 10276 :stringpoint "CURLOPT_TLS13_CIPHERS" NIL NIL NIL)
   (:proxy-tls13-ciphers 10277 :stringpoint "CURLOPT_PROXY_TLS13_CIPHERS" NIL NIL NIL)
   (:disallow-username-in-url 278 :long "CURLOPT_DISALLOW_USERNAME_IN_URL" NIL NIL NIL)
   (:doh-url 10279 :stringpoint "CURLOPT_DOH_URL" NIL NIL NIL)
   (:upload-buffersize 280 :long "CURLOPT_UPLOAD_BUFFERSIZE" NIL NIL NIL)
   (:upkeep-interval-ms 281 :long "CURLOPT_UPKEEP_INTERVAL_MS" NIL NIL NIL)
   (:curlu 10282 :objectpoint "CURLOPT_CURLU" NIL NIL NIL)
   (:trailerfunction 20283 :functionpoint "CURLOPT_TRAILERFUNCTION" NIL NIL NIL)
   (:trailerdata 10284 :cbpoint "CURLOPT_TRAILERDATA" NIL NIL NIL)
   (:http09-allowed 285 :long "CURLOPT_HTTP09_ALLOWED" NIL NIL NIL)
   (:altsvc-ctrl 286 :long "CURLOPT_ALTSVC_CTRL" NIL NIL NIL)
   (:altsvc 10287 :stringpoint "CURLOPT_ALTSVC" NIL NIL NIL)
   (:maxage-conn 288 :long "CURLOPT_MAXAGE_CONN" NIL NIL NIL)
   (:sasl-authzid 10289 :stringpoint "CURLOPT_SASL_AUTHZID" NIL NIL NIL)
   (:mail-rcpt-allowfails 290 :long "CURLOPT_MAIL_RCPT_ALLOWFAILS" NIL NIL NIL)
   (:sslcert-blob 40291 :blob "CURLOPT_SSLCERT_BLOB" NIL NIL NIL)
   (:sslkey-blob 40292 :blob "CURLOPT_SSLKEY_BLOB" NIL NIL NIL)
   (:proxy-sslcert-blob 40293 :blob "CURLOPT_PROXY_SSLCERT_BLOB" NIL NIL NIL)
   (:proxy-sslkey-blob 40294 :blob "CURLOPT_PROXY_SSLKEY_BLOB" NIL NIL NIL)
   (:issuercert-blob 40295 :blob "CURLOPT_ISSUERCERT_BLOB" NIL NIL NIL)
   (:proxy-issuercert 10296 :stringpoint "CURLOPT_PROXY_ISSUERCERT" NIL NIL NIL)
   (:proxy-issuercert-blob 40297 :blob "CURLOPT_PROXY_ISSUERCERT_BLOB" NIL NIL NIL)
   (:ssl-ec-curves 10298 :stringpoint "CURLOPT_SSL_EC_CURVES" NIL NIL NIL)
   (:hsts-ctrl 299 :long "CURLOPT_HSTS_CTRL" NIL NIL NIL)
   (:hsts 10300 :stringpoint "CURLOPT_HSTS" NIL NIL NIL)
   (:hstsreadfunction 20301 :functionpoint "CURLOPT_HSTSREADFUNCTION" NIL NIL NIL)
   (:hstsreaddata 10302 :cbpoint "CURLOPT_HSTSREADDATA" NIL NIL NIL)
   (:hstswritefunction 20303 :functionpoint "CURLOPT_HSTSWRITEFUNCTION" NIL NIL NIL)
   (:hstswritedata 10304 :cbpoint "CURLOPT_HSTSWRITEDATA" NIL NIL NIL)
   (:aws-sigv4 10305 :stringpoint "CURLOPT_AWS_SIGV4" NIL NIL NIL)
   (:doh-ssl-verifypeer 306 :long "CURLOPT_DOH_SSL_VERIFYPEER" NIL NIL NIL)
   (:doh-ssl-verifyhost 307 :long "CURLOPT_DOH_SSL_VERIFYHOST" NIL NIL NIL)
   (:doh-ssl-verifystatus 308 :long "CURLOPT_DOH_SSL_VERIFYSTATUS" NIL NIL NIL)
   (:cainfo-blob 40309 :blob "CURLOPT_CAINFO_BLOB" NIL NIL NIL)
   (:proxy-cainfo-blob 40310 :blob "CURLOPT_PROXY_CAINFO_BLOB" NIL NIL NIL)
   (:ssh-host-public-key-sha256 10311 :stringpoint "CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256" NIL NIL NIL)
   (:prereqfunction 20312 :functionpoint "CURLOPT_PREREQFUNCTION" NIL NIL NIL)
   (:prereqdata 10313 :cbpoint "CURLOPT_PREREQDATA" NIL NIL NIL)
   (:maxlifetime-conn 314 :long "CURLOPT_MAXLIFETIME_CONN" NIL NIL NIL)
   (:mime-options 315 :long "CURLOPT_MIME_OPTIONS" NIL NIL NIL)
   (:ssh-hostkeyfunction 20316 :functionpoint "CURLOPT_SSH_HOSTKEYFUNCTION" NIL NIL NIL)
   (:ssh-hostkeydata 10317 :cbpoint "CURLOPT_SSH_HOSTKEYDATA" NIL NIL NIL)
   (:protocols-str 10318 :stringpoint "CURLOPT_PROTOCOLS_STR" NIL NIL NIL)
   (:redir-protocols-str 10319 :stringpoint "CURLOPT_REDIR_PROTOCOLS_STR" NIL NIL NIL)
   (:ws-options 320 :long "CURLOPT_WS_OPTIONS" NIL NIL NIL)
   (:ca-cache-timeout 321 :long "CURLOPT_CA_CACHE_TIMEOUT" NIL NIL NIL)
   (:quick-exit 322 :long "CURLOPT_QUICK_EXIT" NIL NIL NIL)
   (:haproxy-client-ip 10323 :stringpoint "CURLOPT_HAPROXY_CLIENT_IP" NIL NIL NIL)
   (:server-response-timeout-ms 324 :long "CURLOPT_SERVER_RESPONSE_TIMEOUT_MS" NIL NIL NIL)
   (:ech 10325 :stringpoint "CURLOPT_ECH" NIL NIL NIL)
   (:tcp-keepcnt 326 :long "CURLOPT_TCP_KEEPCNT" NIL NIL NIL)
   (:upload-flags 327 :long "CURLOPT_UPLOAD_FLAGS" NIL NIL NIL)
   (:ssl-signature-algorithms 10328 :stringpoint "CURLOPT_SSL_SIGNATURE_ALGORITHMS" NIL NIL NIL)
   (:httppost 10024 :objectpoint "CURLOPT_HTTPPOST" "7.56.0" "Use CURLOPT_MIMEPOST" NIL)
   (:put 54 :long "CURLOPT_PUT" "7.12.1" "Use CURLOPT_UPLOAD" NIL)
   (:progressfunction 20056 :functionpoint "CURLOPT_PROGRESSFUNCTION" "7.32.0" "Use CURLOPT_XFERINFOFUNCTION" NIL)
   (:krblevel 10063 :stringpoint "CURLOPT_KRBLEVEL" "8.17.0" "removed" NIL)
   (:random-file 10076 :stringpoint "CURLOPT_RANDOM_FILE" "7.84.0" "Serves no purpose anymore" NIL)
   (:egdsocket 10077 :stringpoint "CURLOPT_EGDSOCKET" "7.84.0" "Serves no purpose anymore" NIL)
   (:dns-use-global-cache 91 :long "CURLOPT_DNS_USE_GLOBAL_CACHE" "7.11.1" "Use CURLOPT_SHARE" NIL)
   (:ioctlfunction 20130 :functionpoint "CURLOPT_IOCTLFUNCTION" "7.18.0" "Use CURLOPT_SEEKFUNCTION" NIL)
   (:ioctldata 10131 :cbpoint "CURLOPT_IOCTLDATA" "7.18.0" "Use CURLOPT_SEEKDATA" NIL)
   (:conv-from-network-function 20142 :functionpoint "CURLOPT_CONV_FROM_NETWORK_FUNCTION" "7.82.0" "Serves no purpose anymore" NIL)
   (:conv-to-network-function 20143 :functionpoint "CURLOPT_CONV_TO_NETWORK_FUNCTION" "7.82.0" "Serves no purpose anymore" NIL)
   (:conv-from-utf8-function 20144 :functionpoint "CURLOPT_CONV_FROM_UTF8_FUNCTION" "7.82.0" "Serves no purpose anymore" NIL)
   (:socks5-gssapi-service 10179 :stringpoint "CURLOPT_SOCKS5_GSSAPI_SERVICE" "7.49.0" "Use CURLOPT_PROXY_SERVICE_NAME" NIL)
   (:protocols 181 :long "CURLOPT_PROTOCOLS" "7.85.0" "Use CURLOPT_PROTOCOLS_STR" NIL)
   (:redir-protocols 182 :long "CURLOPT_REDIR_PROTOCOLS" "7.85.0" "Use CURLOPT_REDIR_PROTOCOLS_STR" NIL)
   (:ssl-enable-npn 225 :long "CURLOPT_SSL_ENABLE_NPN" "7.86.0" "Has no function" NIL)
   (:ssl-falsestart 233 :long "CURLOPT_SSL_FALSESTART" "8.15.0" "Has no function" NIL)
   (:stream-depends 10240 :objectpoint "CURLOPT_STREAM_DEPENDS" "8.21.0" "Has no function" NIL)
   (:stream-depends-e 10241 :objectpoint "CURLOPT_STREAM_DEPENDS_E" "8.21.0" "Has no function" NIL)
   (:obsolete72 9999 :long "CURLOPT_OBSOLETE72" "obsolete" NIL NIL)
   (:obsolete40 9999 :long "CURLOPT_OBSOLETE40" "obsolete" NIL NIL)
   (:encoding 10102 :stringpoint "CURLOPT_ENCODING" NIL NIL :ACCEPT-ENCODING)
   (:file 10001 :cbpoint "CURLOPT_FILE" NIL NIL :WRITEDATA)
   (:infile 10009 :cbpoint "CURLOPT_INFILE" NIL NIL :READDATA)
   (:writeheader 10029 :cbpoint "CURLOPT_WRITEHEADER" NIL NIL :HEADERDATA)
   (:writeinfo 9999 :long "CURLOPT_WRITEINFO" "obsolete" NIL :OBSOLETE40)
   (:closepolicy 9999 :long "CURLOPT_CLOSEPOLICY" "obsolete" NIL :OBSOLETE72)
   (:progressdata 10057 :cbpoint "CURLOPT_PROGRESSDATA" NIL NIL :XFERINFODATA)
   (:post301 161 :values "CURLOPT_POST301" NIL NIL :POSTREDIR)
   (:sslkeypasswd 10026 :stringpoint "CURLOPT_SSLKEYPASSWD" NIL NIL :KEYPASSWD)
   (:ftpappend 50 :long "CURLOPT_FTPAPPEND" NIL NIL :APPEND)
   (:ftplistonly 48 :long "CURLOPT_FTPLISTONLY" NIL NIL :DIRLISTONLY)
   (:ftp-ssl 119 :values "CURLOPT_FTP_SSL" NIL NIL :USE-SSL)
   (:sslcertpasswd 10026 :stringpoint "CURLOPT_SSLCERTPASSWD" NIL NIL :KEYPASSWD)
   (:krb4level 10063 :stringpoint "CURLOPT_KRB4LEVEL" "8.17.0" "removed" :KRBLEVEL)
   (:ftp-response-timeout 112 :long "CURLOPT_FTP_RESPONSE_TIMEOUT" NIL NIL :SERVER-RESPONSE-TIMEOUT)
   (:mail-rcpt-alllowfails 290 :long "CURLOPT_MAIL_RCPT_ALLLOWFAILS" NIL NIL :MAIL-RCPT-ALLOWFAILS)
   (:rtspheader 10023 :slistpoint "CURLOPT_RTSPHEADER" NIL NIL :HTTPHEADER)
   ))

(register-multi-options
  '(
   (:socketfunction 20001 :functionpoint "CURLMOPT_SOCKETFUNCTION" NIL NIL NIL)
   (:socketdata 10002 :objectpoint "CURLMOPT_SOCKETDATA" NIL NIL NIL)
   (:pipelining 3 :long "CURLMOPT_PIPELINING" NIL NIL NIL)
   (:timerfunction 20004 :functionpoint "CURLMOPT_TIMERFUNCTION" NIL NIL NIL)
   (:timerdata 10005 :objectpoint "CURLMOPT_TIMERDATA" NIL NIL NIL)
   (:maxconnects 6 :long "CURLMOPT_MAXCONNECTS" NIL NIL NIL)
   (:max-host-connections 7 :long "CURLMOPT_MAX_HOST_CONNECTIONS" NIL NIL NIL)
   (:max-pipeline-length 8 :long "CURLMOPT_MAX_PIPELINE_LENGTH" NIL NIL NIL)
   (:content-length-penalty-size 30009 :off-t "CURLMOPT_CONTENT_LENGTH_PENALTY_SIZE" NIL NIL NIL)
   (:chunk-length-penalty-size 30010 :off-t "CURLMOPT_CHUNK_LENGTH_PENALTY_SIZE" NIL NIL NIL)
   (:pipelining-site-bl 10011 :objectpoint "CURLMOPT_PIPELINING_SITE_BL" NIL NIL NIL)
   (:pipelining-server-bl 10012 :objectpoint "CURLMOPT_PIPELINING_SERVER_BL" NIL NIL NIL)
   (:max-total-connections 13 :long "CURLMOPT_MAX_TOTAL_CONNECTIONS" NIL NIL NIL)
   (:pushfunction 20014 :functionpoint "CURLMOPT_PUSHFUNCTION" NIL NIL NIL)
   (:pushdata 10015 :objectpoint "CURLMOPT_PUSHDATA" NIL NIL NIL)
   (:max-concurrent-streams 16 :long "CURLMOPT_MAX_CONCURRENT_STREAMS" NIL NIL NIL)
   (:network-changed 17 :long "CURLMOPT_NETWORK_CHANGED" NIL NIL NIL)
   (:notifyfunction 20018 :functionpoint "CURLMOPT_NOTIFYFUNCTION" NIL NIL NIL)
   (:notifydata 10019 :objectpoint "CURLMOPT_NOTIFYDATA" NIL NIL NIL)
   (:resolve-threads-max 20 :long "CURLMOPT_RESOLVE_THREADS_MAX" NIL NIL NIL)
   (:quick-exit 21 :long "CURLMOPT_QUICK_EXIT" NIL NIL NIL)
   ))
